### ISSUE TITLE
Update 6.2.0-GA (General Availability) Version 

### ISSUE THREAD

**Issue by jcgut** [Greencorecr/acs-community-deployment#5]
It's completely necessary to change this version for running some modules (third party like Cases Module by Binovo) to 6.2.0-GA (General Availability) in order to work properly.

Adding the following lines:

export ALFREPOWAR=https://artifacts.alfresco.com/nexus/service/local/repositories/releases/content/org/alfresco/content-services-community/6.2.0-ga/content-services-community-6.2.0-ga.war
export ALFSHAREWAR=https://artifacts.alfresco.com/nexus/service/local/repositories/releases/content/org/alfresco/share/6.2.0/share-6.2.0.war
export ALFSHARESERVICES=https://artifacts.alfresco.com/nexus/service/local/repositories/releases/content/org/alfresco/alfresco-share-services/6.2.0/alfresco-share-services-6.2.0.amp

**Comment by fede2cr** [comment]
Applied
